#lang racket
(require racket/trace)

; Exercise 1.15
;
; The sine of an angle (specified in radians) can be computed by making use of the approximation sinx≈x
; if x
; is sufficiently small, and the trigonometric identity
;   sinx=3sinx3−4sin3x3
; to reduce the size of the argument of sin.
; (For purposes of this exercise an angle is considered “sufficiently small” if its magnitude is not greater than 0.1 radians.)
; These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
;
; b. What is the order of growth in space and number of steps (as a function of a)
; used by the process generated by the sine procedure when (sine a) is evaluated?

;;; --------------------------ANSWER:--------------------------------


(trace p)
(trace sine)
(sine 12.15)

; a. Procedure p is applied 5 times.

; b. The space and time complexity will grow based on how many times a needs to be divided by 3.
; This can be expressed as a/3^n < 0.1, where n is the number of times a is divided by 3.
; This can be rewritten as a/0.1 < 3^n, to which logarithms can be applied to achieve log(a/0.1) < n*log(3).
; evaluating to n > log(a/0.1)/log(3).
; Therefore, the time and space complexity is O(log(a))
